# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: terraless
#env:
#  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - binary: terraless
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
dockers:
  - image_templates:
      - "odaniait/terraless:{{ .Tag }}"
      - "odaniait/terraless:v{{ .Major }}"
      - "odaniait/terraless:v{{ .Major }}.{{ .Minor }}"
      - odaniait/terraless:latest
archive:
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

blobs:
  - provider: s3
    bucket: terraless-plugins
    folder: "terraless/{{ .Tag }}"
  - provider: s3
    bucket: terraless-plugins
    folder: "terraless/latest"

# brew:
#   github:
#     owner: Odania-IT
#     name: terraless-tap
#   folder: Formula
#   homepage:  https://github.com/Odania-IT/terraless
#   description: Terraless cloud army swiss knife
#   test: |
#     system "#{bin}/terraless version"
