sudo: false
language: go
env:
  global:
  - GO111MODULE=on
  - secure: E3uqy/QHzPdiuM3s0rNGTELWAI1Z/cKh2Gjlek56ECK/YLEM+TDcKE0u7Y4a0EH/Wyb0W/Fj5UBiO5pfmRA6zW6yusJyD2//xVieD8Tz5juZl1eUx6FI1aZJag19IFIfealg14qBgD4pNuIMvgAWFHRc/H27NJhxvapWOhi7p1AIx4A7ItJ0bwkQzTcRdYZwA9KUw73+BiU8HSQpmgVn/wIXzEg6Ao3UdExmpkGgLa5bhRsCbiWRpuAXOn0liZc3tk+o359CxH+MuNqSbyOluo3MrGvhOyC/22okVCXFn8/5dM0VB3NZg6bJGCdS39C73AzbhiI84eL1FDRJeBFoQVRuwsV9wEhYae9ux2exzbIokslJzhlLunCCrFZ6vELTwEfICL1xHsbO0C2KoDKzo8wxe2JVdbV4OC9jjz1eN7KtVDYdD2u+/ZEx1TElC8Gn1FpmrW69lTPNszRt99CJKfW8aBM3PMjQt7zfYG/wnP1sLcMYIjRHGsIbSyJKIA39e8NQALxIP2CA8o18UEMQEtUsF5DzZkU0bCRvdCo9zyfMP5AP0/STrHb+eABJPVphU/C8IAExq4PhxwfGMBZRKKC+yx7LY5n6kxj2t93JgPPQg7OKgFqjh8RDZumH2/oeMoHmQnNk+ocP0xmVIrDrydpSIKW4H1h83GsbbZEQg9I=
go:
- 1.11.x
git:
  depth: 1
install: true
before_script:
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
script:
- golangci-lint run
- go test -v -race ./...
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
