sudo: false
language: go
env:
  global:
  - GO111MODULE=on
  - AWS_REGION=eu-central-1
  - secure: E3uqy/QHzPdiuM3s0rNGTELWAI1Z/cKh2Gjlek56ECK/YLEM+TDcKE0u7Y4a0EH/Wyb0W/Fj5UBiO5pfmRA6zW6yusJyD2//xVieD8Tz5juZl1eUx6FI1aZJag19IFIfealg14qBgD4pNuIMvgAWFHRc/H27NJhxvapWOhi7p1AIx4A7ItJ0bwkQzTcRdYZwA9KUw73+BiU8HSQpmgVn/wIXzEg6Ao3UdExmpkGgLa5bhRsCbiWRpuAXOn0liZc3tk+o359CxH+MuNqSbyOluo3MrGvhOyC/22okVCXFn8/5dM0VB3NZg6bJGCdS39C73AzbhiI84eL1FDRJeBFoQVRuwsV9wEhYae9ux2exzbIokslJzhlLunCCrFZ6vELTwEfICL1xHsbO0C2KoDKzo8wxe2JVdbV4OC9jjz1eN7KtVDYdD2u+/ZEx1TElC8Gn1FpmrW69lTPNszRt99CJKfW8aBM3PMjQt7zfYG/wnP1sLcMYIjRHGsIbSyJKIA39e8NQALxIP2CA8o18UEMQEtUsF5DzZkU0bCRvdCo9zyfMP5AP0/STrHb+eABJPVphU/C8IAExq4PhxwfGMBZRKKC+yx7LY5n6kxj2t93JgPPQg7OKgFqjh8RDZumH2/oeMoHmQnNk+ocP0xmVIrDrydpSIKW4H1h83GsbbZEQg9I=
  - secure: aiiSVQu9rIdEiOX198gmx43rnJiMiJNqdF5h4XH7CICgJ7xd8TgkaPSjwcOzhGlkguDchPeshS0H5D7tbKc6r8oCMoeYVPfuJ3a0sYUHTdDb81oBUtsWdqrYkyYiJUmqBbGyyS1jwhXTGyqhDK0cxAqE8Lf5t2jQFYg838vlyBZLUG1Mt9/woHBOXwRMmgWRVhHbT4hVIUi5yCMp5A4qu//YXOgS362O9AVJM7P8qjqjNVBx9Ougt5m357zvhDiWZonvgbiccEGFjvulzYmykECeFwDtgz8xu60H7QLsQXgs3nodHbU3iNP7ToKAu8tyuoekolm07L5DH/mOfj1xKWQjIay/FrYtXaIv9Fxx27W+9sTOftikc4AfynoIcWmYZcD39k9vJDOzyVqGchA+U8EFAvTlxDrHdBkrtpdW3zUf0I09PwxM6k8GlkQ7qPJ3gJ/+crQCztJbMzfzJDy7+hQWphOL8Z/Y14/DLdiui+tv7Uk6FjKDDlNfbDt9tkQzq0sA5GV0S1//G+ZEy1vBI3/vJR3SUv2CqIcMv2nU7Y72uaCdMEgz/UwWHlJSk6rUPkAFIGpPkk86EcOh2RpZUAjwj2q+Ptn8/bqMh5MBNV9XAlV0KCNMH13U44LF3d2At184T69513Wu62i/3sTV5vJALa8XWwJrzAS2D5okh04=
  - secure: kUO5oNAZ96an4frGh/nCIGYXlo6tY6+Wp+O9IhBBvzh7pJwC7E+0enCOQ6mKtIrlDj6In9LCvcIXTa6LC7B5UaK92JavrFNFmePFKBy7ey+JfSneeVeJlH8QKUd8LJagyuXLSxgOkEpH1JpUh26/FEANRmYv1tRg7NZHN2tIk9UEnQSOeiNz/Ea6pHzKDqwxs1NVv+xjx2P0SzQjRTr8HNMtFq4CKGTZbPB+W1mhGiUsXiJFmfGgrR8NSZBBk3xBYDbW6N3gO/Zj4GsdEm5B/5AVPRYAbAT7YGwa6DVLNQiymjuvuPwkPnpoYFVtYlLwkrW+EwUnAEwKhht0Ae5e3Gk1v+RSCS0WQa62aH2DcnxfvUwjIGEXHQMAZDJWxhX7tE+5s9jv3eOHH4+J9OkgHlVs2AjBGRkcCRHJatZ/NfCUimEyxxbN1R76zpXoxq3AlBk8dzOEtKlpwcSLB8YaCmWn7sKLxxu0S1W/xVoGPOrtJQd5MeBFUewliERlzyPzu9KuCeNLtzhwFVwz8pBSmehBfm6FdT/jdzNsqKNfV13l0PIK96cljYVSey8yXm02XWw+MMOuoRm168Uv347EAjIOpMuTRkiwhYdoPgk2/OYufsad0VcDXW0AlYQ3f3dZc5aMycANbv/4IavTqYIe1B/K2nQtshfsaKBKQA45cKI=
  - secure: lZib2iAjbJlTazshJ5dnaEVR1lSrp320hsdyfFATtOE/POsxqDWwsWWeETig4jC/fW5PGkTEKGi41lOloOpILJufShcun8x1GLo2F9Xv50NzUxQa7cYEPPvvW7HF/c6/qlIDyEMPCYXyQObzrWMl41z+CnQtjmPnIqKk58FPClXj72wQn6gBF6hTAlNzpjOGLZH3zZGwFmiQKr1QcsTgJWt+htiZ4A6jl7cBo6lJ1jTQmOmKmPk+L0CtNXWTL9Y722CLdoVlMagn2Irvq9/+cpb8kacfNcEVnJJGR4+6jEdL8Pxa9TeKEViVO3PKKRI5OoGsZw/yCJHD1030kBR4kr/cdjSNH1rY1qwnsV/v6Hughwp9xGW0v46zwB5ujdO4dknBxO7NMUu0ktrm2HpLt3woeXjBu+1bLVR8mbRHoQPWgF0TeGR/5y3Ccs7tamv+YY0ds+RDOo4mzuZL5sJyHTFyOL33ZICKIouT9CQmHHbiK3vtZpIFv7iJyGx9zPZlZ4sdV2S4vOHLpu7BfFGZfSpgagS/NQddm+RMCDKRlekOn5BNDvz89U6SXcuZdxZMj8di9bb7uXx9SPwDF/EIGQZtqYPwT4TY+HAm5ADS9zVoMMRvMcgth8G/h8DpHUEkx6z8CQwvelT/Cj+wcbzKiuDppa/ZQ7Emv5n8wxadEo0=
go:
  - 1.11.x
services:
  - docker
install: true
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - go get github.com/gobuffalo/packr/v2/packr2
  - packr2
script:
  - golangci-lint run
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash -c 'git checkout go.mod go.sum'
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - git status
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
