package terraless_provider_aws

var eventTemplates = map[string]string{
	"http": `# This file is generated by Terraless

resource "aws_api_gateway_rest_api" "terraless-api-gateway" {
  name        = "{{ .Config.ProjectName }}-{{ .Arguments.Environment }}"
  description = "Terraless Api Gateway for {{ .Config.ProjectName }}-{{ .Arguments.Environment }}"
}

resource "aws_api_gateway_resource" "terraless-api-gateway-proxy" {
  rest_api_id = "${aws_api_gateway_rest_api.terraless-api-gateway.id}"
  parent_id   = "${aws_api_gateway_rest_api.terraless-api-gateway.root_resource_id}"
  path_part   = "{proxy+}"
}

resource "aws_api_gateway_method" "terraless-api-gateway-proxy" {
  rest_api_id   = "${aws_api_gateway_rest_api.terraless-api-gateway.id}"
  resource_id   = "${aws_api_gateway_resource.terraless-api-gateway-proxy.id}"
  http_method   = "ANY"
  authorization = "NONE"
}

resource "aws_api_gateway_method" "terraless-api-gateway-proxy-root" {
  rest_api_id   = "${aws_api_gateway_rest_api.terraless-api-gateway.id}"
  resource_id   = "${aws_api_gateway_rest_api.terraless-api-gateway.root_resource_id}"
  http_method   = "ANY"
  authorization = "NONE"
}

`,
}

var IntegrationTemplates = map[string]string{
	"http": `
# Function {{ .FunctionName }}

resource "aws_api_gateway_integration" "terraless-lambda-{{.FunctionName}}" {
  rest_api_id = "${aws_api_gateway_rest_api.terraless-api-gateway.id}"
  resource_id = "${aws_api_gateway_method.terraless-api-gateway-proxy.resource_id}"
  http_method = "${aws_api_gateway_method.terraless-api-gateway-proxy.http_method}"

  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = "${aws_lambda_function.lambda-{{.FunctionName}}.invoke_arn}"
}

`,
	"sqs": `
# Function {{ .FunctionName }}
`,
}
